-dontwarn **
-dontobfuscate
-keep class org.codehaus.groovy.vmplugin.**
-keep class org.codehaus.groovy.runtime.** { *; }
-keep class org.codehaus.groovy.reflection.** { *; }
-keep class org.codehaus.groovy.util.** { *; }
